import { Container, Flex, Heading, Link as ChakraLink, Stack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const ErrorPage: NextPage = () => {
  return (
    <Container maxW='2xl'>
      <Head>
        <title>ESP Tech Stack PoC | Error</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex py={16} minH='100vh' direction='column' justify='center' align='center'>
        <main>
          <Heading as='h2' size='xl' mb={8} color='red.600'>
            Error
          </Heading>

          <Stack mb={4}>
            <p>There was a problem with your submission 🙁</p>
          </Stack>

          <Stack mb={8}>
            <Link href='/' passHref>
              <ChakraLink color='blue.500'>Go back to home.</ChakraLink>
            </Link>
          </Stack>
        </main>
      </Flex>
    </Container>
  );
};

export default ErrorPage;
