import {
  Button,
  Center,
  Container,
  Flex,
  Heading,
  Link as ChakraLink,
  Stack,
  Text
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const HomePage: NextPage = () => {
  const router = useRouter();

  return (
    <Container maxW='2xl'>
      <Head>
        <title>ESP Tech Stack PoC</title>
        <meta name='description' content='Generated by create next app' />
        <meta httpEquiv='Content-Type' content='text/html; charset=UTF-8'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex py={16} minH='100vh' direction='column' justify='center' align='center'>
        <main>
          <Center>
            <Heading as='h1' size='2xl' mb={4}>
              ESP Tech Stack PoC
            </Heading>
          </Center>

          <Center>
            <Stack mb={16}>
              <p>
                Built just for testing Web-to-Lead forms, using the tech stack being discussed{' '}
                <ChakraLink
                  color='blue.500'
                  href='https://www.notion.so/efdn/f4e910fa39c5411f805466aca2cadf7d?v=f90fa873a26c43318468890d4bf6d6c0&p=7f56742b50a743a6aa3c892e7606e9b3'
                  isExternal
                >
                  here.
                </ChakraLink>
              </p>
            </Stack>
          </Center>

          <Heading as='h2' size='xl' mb={4}>
            Contact Us
          </Heading>

          <Stack mb={16}>
            <p>
              Whether you&apos;re working on a specific project, or you&apos;re still exploring
              possibilities, you can connect with our team for guidance.
            </p>
          </Stack>

          <Center>
            <Button colorScheme='blue' onClick={() => router.push('/inquire')}>
              <Text size='3xl'>Submit an inquiry</Text>
            </Button>
          </Center>
        </main>
      </Flex>
    </Container>
  );
};

export default HomePage;
