import {
  Box,
  Button,
  Checkbox,
  Container,
  Flex,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  Input,
  Link as ChakraLink,
  Select,
  Stack,
  Textarea
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>ESP Tech Stack PoC</title>
        <meta name='description' content='Generated by create next app' />
        <meta httpEquiv='Content-Type' content='text/html; charset=UTF-8'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex py={16} minH='100vh' direction='column' justify='center' align='center'>
        <main>
          <Heading as='h1' size='2xl' mb={4}>
            ESP Tech Stack PoC
          </Heading>

          <Stack mb={16}>
            <p>
              PoC for the ESP Web-to-Lead forms, using the tech stack being discussed{' '}
              <ChakraLink
                color='blue.500'
                href='https://www.notion.so/efdn/f4e910fa39c5411f805466aca2cadf7d?v=f90fa873a26c43318468890d4bf6d6c0&p=7f56742b50a743a6aa3c892e7606e9b3'
                isExternal
              >
                here.
              </ChakraLink>
            </p>
          </Stack>

          {/* SF Web-to-Lead form sample */}
          <Box w={['full', '2xl']} p={[8, 10]} backgroundColor='gray.50' rounded={6}>
            <form
              action='https://test.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8'
              method='POST'
            >
              <input type='hidden' name='oid' value='00D5E000000DkPC' />
              <input type='hidden' name='retURL' value='http://' />
              {/*
              <!--  ----------------------------------------------------------------------  -->
              <!--  NOTE: These fields are optional debugging elements. Please uncomment    -->
              <!--  these lines if you wish to test in debug mode.                          -->
              <!--  <input type="hidden" name="debug" value=1>                              -->
              <!--  <input type="hidden" name="debugEmail" value="nh.quiroz@gmail.com">     -->
              <!--  ----------------------------------------------------------------------  -->
            */}
              <Stack spacing={6} align='flex-start'>
                <FormControl id='first_name' isRequired>
                  <FormLabel htmlFor='first_name'>Your name</FormLabel>
                  <Input id='first_name' maxLength={40} name='first_name' type='text' bg='white' />
                  <FormHelperText>
                    Use whichever preferred name you would like our team to address you by.
                  </FormHelperText>
                </FormControl>

                <FormControl id='email' isRequired>
                  <FormLabel htmlFor='email'>Contact email</FormLabel>
                  <Input id='email' maxLength={80} name='email' type='email' bg='white' />
                </FormControl>

                <FormControl id='first_name'>
                  <FormLabel htmlFor='company'>Project or company name</FormLabel>
                  <Input id='company' maxLength={40} name='company' type='text' bg='white' />
                </FormControl>

                <FormControl id='00N5J000000QWsP' isRequired>
                  <FormLabel htmlFor='inquiry_type'>What are you getting in touch about?</FormLabel>
                  <Select
                    name='00N5J000000QWsP'
                    title='Type of Inquiry'
                    placeholder='Select...'
                    bg='white'
                  >
                    <option value='Project'>Project</option>
                    <option value='Exploring Possibilities'>Exploring Possibilities</option>
                    <option value='Sponsorship'>Sponsorship</option>
                  </Select>
                </FormControl>

                <FormControl id='description' isRequired>
                  <FormLabel htmlFor='description'>
                    Briefly enter your question, comment or reason for contacting us below
                  </FormLabel>
                  <Textarea name='description' bg='white' />
                </FormControl>

                <Stack>
                  <Checkbox>
                    Subscribe to the ESP Newsletter? You&apos;ll hear from us every few weeks, and
                    we&apos;ll only ever contact you with ESP news.
                  </Checkbox>
                </Stack>

                <Button colorScheme='blue' px={8} py={6}>
                  Submit
                </Button>
              </Stack>
            </form>
          </Box>
        </main>
      </Flex>
    </Container>
  );
};

export default Home;
