import { Container, Flex, Heading, Stack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const ThanksPage: NextPage = () => {
  const router = useRouter();

  return (
    <Container maxW='2xl'>
      <Head>
        <title>ESP Tech Stack PoC</title>
        <meta name='description' content='Generated by create next app' />
        <meta httpEquiv='Content-Type' content='text/html; charset=UTF-8'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex py={16} minH='100vh' direction='column' justify='center' align='center'>
        <main>
          <Heading as='h2' size='xl' mb={4}>
            Thanks!
          </Heading>

          <Stack mb={16}>
            <p>
              Whether you&apos;re working on a specific project, or you&apos;re still exploring
              possibilities, you can connect with our team for guidance.
            </p>
          </Stack>
        </main>
      </Flex>
    </Container>
  );
};

export default ThanksPage;
